### ISSUE TITLE
Unfriendly behavior when schema contains invalid link

### ISSUE THREAD

**Issue by flack** [midgardproject/midgard-php5#119]
If one of your schemas has a link to a nonexistent schema class like this

``` xml
<property name="linktonowhere" type="unsigned integer" link="not_installed_schema:id">
```

Then you get the following for every PHP command (even if it doesn't involve midgard):

```
midgard-core-ERROR **: Can not get link class for linktonowhere.not_installed_schema

Program received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffff01c82c5 in g_logv () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
(gdb) backtrace
#0  0x00007ffff01c82c5 in g_logv () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007ffff01c8492 in g_log () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff072a4f6 in __is_linked_valid (klass=0x12195f0, prop=0x1078380 "linktonowhere")
    at src/mgdschema.c:1275
#3  0x00007ffff072ce82 in __midgard_schema_validate () at src/mgdschema.c:1332
#4  midgard_schema_read_dir (self=<optimized out>, 
    dirname=dirname@entry=0x10d1b00 "/usr/share/midgard2") at src/mgdschema.c:1684
#5  0x00007ffff097e7fc in php_midgard_initialize_schema ()
    at /home/sonic/workspace/midgard-php5/midgard.c:314
#6  zm_startup_midgard2 (type=1, module_number=49)
    at /home/sonic/workspace/midgard-php5/midgard.c:368
#7  0x00000000006db806 in zend_startup_module_ex ()
#8  0x00000000006e7cb5 in zend_hash_apply ()
#9  0x00000000006df71a in zend_startup_modules ()
#10 0x000000000067947b in php_module_startup ()
#11 0x000000000078aa3d in ?? ()
#12 0x00000000004647ac in main ()
```

The problem is that it really affects everything you do with PHP, and schemas are global, so you don't only break one project, but everything PHP on this machine. I wonder if this could be changed to something less intrusive. IMHO, it would be enough if in situations like this, a warning is printed (and of course, the schema with the broken link would not be available as a PHP class)

**Comment by piotras** [comment]
This is correct. Midgard module (and schemas, and classes) are initialized during PHP startup. It's up to PHP how to exclude particular module, if it's not used and not required per running application. Ignoring class throwing an error is not an option. Core itself is not responsible to create such logic and make decision what might be ignored and what might be not.
