### ISSUE TITLE
Unexpected warnings thrown when initializing QueryBuilder for midgard_user

### ISSUE THREAD

**Issue by piotras** [midgardproject/midgard-php5#14]
$qb = new midgard_query_builder('midgard_user'); 
throws:
Warning: Expected MidgardDBObject derived class 

$qb = new midgard_query_builder('MidgardUser'); 
throws:
Fatal error: Class 'MidgardUser' not found

**Comment by indeyets** [comment]
fixed in trunk and ratatoskr branches. test is written
