### ISSUE TITLE
Expose Midgard configuration through midgard_key_config to PHP

### ISSUE THREAD

**Issue by bergie** [midgardproject/midgard-php5#2]
With [Trac ticket 1341](http://trac.midgard-project.org/ticket/1341) it would be very useful if Midgard configuration file used for the request could be used to manipulate parts of Midgard MVC configuration.

It is important to not to expose confidential information like database account, but still provide parts of the config to PHP apps.

**Comment by indeyets** [comment]
related functionality was implemented in core for 10.05.1. connection has "config" property now

we need to verify if that was enough or more should be done

**Comment by bergie** [comment]
This is well enough.
