### ISSUE TITLE
Inconsistent error handling in object constructor

### ISSUE THREAD

**Issue by flack** [midgardproject/midgard-php5#20]
The following throws a midgard_error_exception (if no article 29 can be found):

$a = new midgard_article('29');

This returns an empty object with no indication of an error:

$a = new midgard_article('2f');

This triggers PHP Warning:  Wrong id-type for 'midgard_article' constructor:

$a = new midgard_article(false);

Especially the first and the second example should really behave identically, i.e. throw an exception. The third one might be the developer's own fault, but of course, having a proper exception couldn't hurt either.

**Comment by indeyets** [comment]
fixed by e6ca3df98153f59bdc45920fc9281a3e2a20dbdc
tested by 8869af238b5ff7ecf6b8e4c8251cc8ffab2ec599

will throw InvalidArgumentException on wrong input and midgard_error_exception if no article can be found
