### ISSUE TITLE
Can not get QuerySelect constraint property

### ISSUE THREAD

**Issue by piotras** [midgardproject/midgard-php5#23]
This happens with recent midgard-core:

$q->set_constraint (
    new midgard_query_constraint (
        new midgard_query_property ("name"),
        "=",
        new midgard_query_value ("A")));
$ca = $q->constraint;

PHP Fatal error:  Class 'MidgardQueryConstraint' is not registered 

Related to https://github.com/midgardproject/midgard-core/issues/issue/61

**Comment by indeyets** [comment]
fixed by 0e718308ddf4026d79b8a85501559302d3477fe9
