### ISSUE TITLE
Extended MgdSchema types are not seen as extending their parent type in PHP

### ISSUE THREAD

**Issue by bergie** [midgardproject/midgard-php5#3]
I have the following schema type:

```
<type name="net_nemein_avaudu_contact" extends="midgard_person">
```

If I look at it using midgard_reflection_class, it seems the class extends midgard_object on PHP level instead of midgard_person.

(copied from http://trac.midgard-project.org/ticket/1540)

**Comment by indeyets** [comment]
discussed this with piotras.

fixing this, would require:
1. change core, to provide hierarchy of classes
2. change midgard-php, to init hierarchy of classes, and not only direct descendants of midgard_object

**Comment by bergie** [comment]
This is very important in situations where code does checks like `is_a($object, 'midgard_person')`
