### ISSUE TITLE
generic method for core <--> php class renames

### ISSUE THREAD

**Issue by indeyets** [midgardproject/midgard-php5#34]
At the moment, class renames are handled on case-by-case basis using php_class_name_to_g_class_name() and g_class_name_to_php_class_name() functions.

generic internal API for registering such renames should be introduced. I believe, internally it should be implemented as 2 hash-tables (for direct and reverse transformation). We should have:

php_midgard_class_rename_register("GlibClassName", "php_class_name");

and initializer/destructor for these hashes in MINIT

**Comment by piotras** [comment]
@indeyets Can we register class names as is and for backward compatibility register their aliases?

**Comment by indeyets** [comment]
They can form hierarchy. "as-is" classes for base, "backwards compatible" as their direct descendants.

**Comment by piotras** [comment]
@indeyets Tried both solutions. With 'midgard_query_executor' being child class of 'MidgardQueryExecutor' reflector doesn't provide signals list. With an alias ('midgard_query_executor' is an alias to 'MidgardQueryExecutor') , it does in both cases.
