### ISSUE TITLE
midgard_connection::get_instance() returns null

### ISSUE THREAD

**Issue by flack** [midgardproject/midgard-php5#35]
In current ratatoskr branch, this call

```
var_dump(midgard_connection::get_instance());
```

returns null, so the system is completely inaccessible. If I revert about ten days back, everything works again, but I didn't try to narrow it down further

**Comment by indeyets** [comment]
that's work-in-progress. wait a bit :)

**Comment by indeyets** [comment]
Can you reproduce this with core and midgard-php5 from today?

**Comment by indeyets** [comment]
bogus

**Comment by flack** [comment]
Small followup question to this: Yesterday, I upgraded my php5-midgard2 repo again, did pake re && pake install && /etc/init.d/lighttpd restart and I'm having the same problem again: midgard_connection::get_instance() returns null and my server is inaccessible. Is this something I'm doing wrong when building/installing the package or is it the current HEAD revision that for some reason is faulty?

**Comment by indeyets** [comment]
@flack there are no known issues like that at the moment. can you come to irc?
