### ISSUE TITLE
More inconsistencies in object constructor

### ISSUE THREAD

**Issue by flack** [midgardproject/midgard-php5#36]
Since #20, the following throws an InvaliArgumentException:

```
$t = new midgard_topic('');
```

This, however, returns an empty object:

```
$t = new midgard_topic(0);
```

So I was wondering: Is this a bug or a feature of some sorts?

BTW, 

```
$t = new midgard_topic(-1);
```

and all other negative values also return objects, which definitely looks like a bug

**Comment by bergie** [comment]
Agreed, 0 and negative integers (and strings that are not GUIDs) should throw exceptions

**Comment by indeyets** [comment]
I added test for this in 522c4bb335b3596cad7f7791eaabb1130e3e938d (failing at the moment). it should be fixed in core. I'll submit ticket

**Comment by indeyets** [comment]
core issue: midgardproject/midgard-core#75
