### ISSUE TITLE
midgard_query_select and midgard_query_executor signals not visible via reflection

### ISSUE THREAD

**Issue by bergie** [midgardproject/midgard-php5#37]
If I list signals for `midgard_object`, I get a full list. But for the `midgard_query_*` classes I don't see the signals I expect to be there, like:
- execution-start
- execution-end

I'm using this for getting signals:

```
    $reflectionclass = new midgard_reflection_class($class);
    $signals = $reflectionclass->listSignals();
```

**Comment by indeyets** [comment]
depends on midgardproject/midgard-php5#34

**Comment by piotras** [comment]
The case might be fact that both classes: QueryExecutor and QuerySelect are not initialized when signals information is requested.
