### ISSUE TITLE
Make configuration of a midgard_query_select accessible

### ISSUE THREAD

**Issue by bergie** [midgardproject/midgard-php5#38]
Use case: we have an access control service that wants to amend all database queries to ensure user cannot read anything they're not supposed to.

To do this, we register a listened for the `execution-start` signal of `midgard_query_select`. But currently our callback will not really get the information it needs about the query:
- What constraints have been set already
- What type is being queried

**Comment by piotras** [comment]
This is available in all query classes. Either as properties or particular methods, so every QuerySelect can be "parameterized".
