### ISSUE TITLE
print_r on midgard_object consumes too much resources

### ISSUE THREAD

**Issue by piotras** [midgardproject/midgard-php5#48]
I know it's metadata and datetime object, which expose circular references. Problem is related to PHPUnit which (while checking objects equality) makes a diff from print_r output. It triggers "allowed memory exhausted..." error and makes tests useless (broken). If it's not easily fixable, I'll try to file a feature request for PHPUnit which could use serialized object to compare instead of print_r.

**Comment by indeyets** [comment]
Can you provide isolated test case for this? In form of "phpt" file, preferably.

**Comment by piotras** [comment]
Please close this as invalid. I didn't realize it's related to number of objects being included in print_r output.
