### ISSUE TITLE
midgard_blob::read_content() segfaults PHP

### ISSUE THREAD

**Issue by feri** [midgardproject/midgard-php5#68]
Environment: Debian unstable 
Midgard version: 10.05.6-1 (packages installed from OBS a week ago approx.)

I have an attachment object (midgard_attachment). Trying to get the corresponding blob to overwrite its content:

<pre>
$blob = new midgard_blob($attachment);
$handler = $blob->get_handler('wb');
$content = $blob->read_content();
</pre>

I get the following error:

<pre>
Warning: Failed to get blob-contents: Critical internal error.   in /home/sopi/work/midgard2/com_meego_obsconnector/api/OBSFetcher.php on line 596
</pre>

dmesg shows this:

<pre>
[82747.670277] php[10817]: segfault at 8 ip 00007f2cfc18e470 sp 00007ffff87003d0 error 4 in libmidgard2.so.2010.5.0[7f2cfc13f000+88000]
</pre>

**Comment by feri** [comment]
Note, that the 'w' flag in PHP will truncate the file. So read_content() segfaults only if the file has no content.

**Comment by piotras** [comment]
Fixed with midgard2-core commit https://github.com/midgardproject/midgard-core/commit/515f308af0133092a610b075e631c18befd6a889
