### ISSUE TITLE
uninstalling the php extension does not remove /etc/php5/conf.d/midgard2.ini

### ISSUE THREAD

**Issue by dbu** [midgardproject/midgard-php5#88]
not sure if this is the right repo to report this, but uninstalling php5-midgard2 on ubunto 12.04 did not clean the conf.d file, leading to an error message about the missing midgard2.so module each time php is used.

**Comment by piotras** [comment]
It's removed when packaged is purged. In debian sid there's already php5dismod involved.

**Comment by piotras** [comment]
Actually not a bug as php doesn't provide any rules or mechanisms to manage ini files.

**Comment by dbu** [comment]
i was talking about the debian packaging. i think uninstalling a package should remove the files installed, including files dropped into the conf.d directory.

**Comment by piotras** [comment]
I am not 100% sure. Can not find proper policy doc roght now. But I reckon, config file should be removed only when package is purged. If that is invalid, please report package bug directly: http://packages.qa.debian.org/p/php5-midgard2.html

**Comment by dbu** [comment]
ah, that is the place to report it. thanks.
