### ISSUE TITLE
Warning when running midgard via Apache

### ISSUE THREAD

**Issue by flack** [midgardproject/midgard-php5#90]
For every request I do against an Apache server on Ubuntu 12.04 with a self-compiled mgd2 running, I get the following entry in error.log:

```
** (process:7880): WARNING **: Error creating user specific configuration directory '/var/www/.local/share/libgda'
```

I suspect that "/var/www/" is Ubuntu's default home directory for the www-data user or something. It would be good if this configuration would run without errors.

**Comment by piotras** [comment]
Created libgda ticket:
https://bugzilla.gnome.org/show_bug.cgi?id=683262

**Comment by seydu** [comment]
Yes, i think it is.
