### ISSUE TITLE
Extension loading fails under PHP 5.4

### ISSUE THREAD

**Issue by flack** [midgardproject/midgard-php5#94]
I just tried installing php 5.4 from a PPA on Ubuntu 12.04. Afterwards, I compiled midgard-php5 with pake re && pake install. Afterwards, I get the following error when running any PHP code:

```
 PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20100525/midgard2.so' - /usr/lib/php5/20100525/midgard2.so: undefined symbol: midgard_sql_query_constraint_get_holder in Unknown on line 0
```

Not sure if it has something to do with my local configuration, so if there's something I did wrong, please let me know!

**Comment by piotras** [comment]
Duplicates https://github.com/midgardproject/midgard-core/issues/165. Already fixed.
